import type { AgentNode } from "./types";

export function createAgent(seed: Partial<AgentNode>): AgentNode {
  return {
    id: "",
    name: "",
    shortName: "",
    role: "",
    emoji: "",
    deptId: null,
    status: "idle",
    currentTask: "Standing by",
    thoughts: [],
    tools: { read: false, write: false, bash: false, db: false },
    tokens: 0,
    progress: 0,
    spawnedAt: -1,
    ...seed,
  };
}

export const AGENT_SEEDS: Array<Partial<AgentNode>> = [
  createAgent({
    id: "ceo",
    name: "CEO / Master Orchestrator",
    shortName: "CEO",
    role: "Master Orchestrator",
    emoji: "🧠",
    deptId: null,
    tools: { read: true, write: true, bash: true, db: false },
  }),

  createAgent({
    id: "head-prod",
    name: "Head of Product",
    shortName: "Head Prod",
    role: "Product Leadership",
    emoji: "📦",
    deptId: "ceo",
    tools: { read: true, write: true, bash: false, db: false },
  }),
  createAgent({
    id: "pm",
    name: "Product Manager",
    shortName: "PM",
    role: "Product",
    emoji: "📋",
    deptId: "head-prod",
    tools: { read: true, write: true, bash: false, db: true },
  }),
  createAgent({
    id: "ux",
    name: "UX Designer",
    shortName: "UX",
    role: "Design",
    emoji: "🎨",
    deptId: "head-prod",
    tools: { read: true, write: true, bash: false, db: false },
  }),
  createAgent({
    id: "fe",
    name: "Front-End Engineer",
    shortName: "FE",
    role: "Engineering",
    emoji: "💻",
    deptId: "head-prod",
    tools: { read: true, write: true, bash: true, db: false },
  }),
  createAgent({
    id: "be",
    name: "Back-End Engineer",
    shortName: "BE",
    role: "Engineering",
    emoji: "⚙️",
    deptId: "head-prod",
    tools: { read: true, write: true, bash: true, db: true },
  }),
  createAgent({
    id: "mb",
    name: "Mobile Engineer",
    shortName: "MB",
    role: "Engineering",
    emoji: "📱",
    deptId: "head-prod",
    tools: { read: true, write: true, bash: true, db: false },
  }),
  createAgent({
    id: "sec",
    name: "Security Engineer",
    shortName: "SEC",
    role: "Security",
    emoji: "🛡️",
    deptId: "head-prod",
    tools: { read: true, write: true, bash: true, db: true },
  }),
  createAgent({
    id: "qa",
    name: "Quality Assurance",
    shortName: "QA",
    role: "Quality",
    emoji: "🧪",
    deptId: "head-prod",
    tools: { read: true, write: true, bash: true, db: false },
  }),

  createAgent({
    id: "head-growth",
    name: "Head of Growth",
    shortName: "Head Grw",
    role: "Growth Leadership",
    emoji: "📈",
    deptId: "ceo",
    tools: { read: true, write: true, bash: false, db: true },
  }),
  createAgent({
    id: "gh",
    name: "Growth Hacker",
    shortName: "GH",
    role: "Growth",
    emoji: "🚀",
    deptId: "head-growth",
    tools: { read: true, write: true, bash: false, db: true },
  }),
  createAgent({
    id: "pf",
    name: "Performance Marketer",
    shortName: "Perf",
    role: "Growth",
    emoji: "💰",
    deptId: "head-growth",
    tools: { read: true, write: true, bash: false, db: true },
  }),
  createAgent({
    id: "seo",
    name: "SEO Specialist",
    shortName: "SEO",
    role: "Growth",
    emoji: "🔍",
    deptId: "head-growth",
    tools: { read: true, write: false, bash: false, db: true },
  }),
  createAgent({
    id: "cc",
    name: "Content Creator",
    shortName: "CC",
    role: "Growth",
    emoji: "✍️",
    deptId: "head-growth",
    tools: { read: true, write: true, bash: false, db: false },
  }),
  createAgent({
    id: "dm",
    name: "Digital Marketer",
    shortName: "DM",
    role: "Growth",
    emoji: "📡",
    deptId: "head-growth",
    tools: { read: true, write: true, bash: false, db: true },
  }),

  createAgent({
    id: "head-biz",
    name: "Head of Biz & Data",
    shortName: "Head Biz",
    role: "Business Leadership",
    emoji: "💼",
    deptId: "ceo",
    tools: { read: true, write: true, bash: false, db: true },
  }),
  createAgent({
    id: "bd",
    name: "Business Developer",
    shortName: "BD",
    role: "Business",
    emoji: "🤝",
    deptId: "head-biz",
    tools: { read: true, write: true, bash: false, db: false },
  }),
  createAgent({
    id: "da",
    name: "Data Analyst",
    shortName: "DA",
    role: "Data",
    emoji: "📊",
    deptId: "head-biz",
    tools: { read: true, write: false, bash: true, db: true },
  }),
];

export const AGENTS: AgentNode[] = AGENT_SEEDS.map((a) => createAgent(a));

export function getChildren(agents: AgentNode[], deptId: string | null): AgentNode[] {
  return agents.filter((a) => a.deptId === deptId);
}
